-- ============================================================
-- Migration: 20260219000000_create_nexus_card_fn.sql
-- Creates stored procedure for reliable nexus_cards insertion.
--
-- Purpose: Eliminate schema-error INSERT failures by providing
-- a single validated entry point for card creation. Handles
-- project slug→UUID resolution, enum validation with clear
-- error messages, parent card lookup, and optional task_details.
--
-- Usage:
--   SELECT * FROM create_nexus_card('council', 'My card title');
--
--   SELECT * FROM create_nexus_card(
--     p_project_slug   => 'nexus',
--     p_title          => 'Add sprint chart',
--     p_delegation_tag => 'BENDER',
--     p_assigned_to    => 'atlas',
--     p_overview       => 'Build recharts widget...'
--   );
--
-- Returns: (out_card_id TEXT, out_card_uuid UUID, out_project_slug TEXT)
-- card_id is auto-generated by nexus_card_auto_id trigger (e.g. 'DEA-112')
-- ============================================================

CREATE OR REPLACE FUNCTION create_nexus_card(
  -- Required
  p_project_slug            TEXT,
  p_title                   TEXT,

  -- Card classification (all have safe defaults)
  p_card_type               TEXT    DEFAULT 'task',
  p_summary                 TEXT    DEFAULT NULL,
  p_lane                    TEXT    DEFAULT 'backlog',
  p_priority                TEXT    DEFAULT 'normal',
  p_delegation_tag          TEXT    DEFAULT 'DEA',
  p_delegation_justification TEXT   DEFAULT NULL,

  -- Assignment
  p_assigned_to             TEXT    DEFAULT NULL,   -- bender slug e.g. 'atlas'
  p_assigned_model          TEXT    DEFAULT NULL,   -- 'gemini', 'claude'
  p_source                  TEXT    DEFAULT NULL,   -- plan ref e.g. 'DEA-235'

  -- Relationships
  p_parent_card_id          TEXT    DEFAULT NULL,   -- e.g. 'DEA-200' (resolved to UUID)
  p_tags                    TEXT[]  DEFAULT '{}',
  p_bender_lane             TEXT    DEFAULT NULL,   -- set for bender-tracked cards

  -- nexus_task_details (row created ONLY if p_overview IS NOT NULL)
  p_overview                TEXT    DEFAULT NULL,
  p_requirements            TEXT    DEFAULT NULL,   -- plain text, not array
  p_acceptance_criteria     TEXT    DEFAULT NULL,   -- plain text, not array
  p_deliverables            TEXT    DEFAULT NULL,
  p_constraints             TEXT    DEFAULT NULL
)
RETURNS TABLE (
  out_card_id      TEXT,
  out_card_uuid    UUID,
  out_project_slug TEXT
)
LANGUAGE plpgsql
AS $$
DECLARE
  v_project_id  UUID;
  v_parent_uuid UUID;
  v_card_uuid   UUID;
  v_card_id     TEXT;

  -- Enum arrays mirror live DB CHECK constraints exactly
  v_valid_lanes TEXT[] := ARRAY[
    'backlog', 'ready', 'in_progress', 'review', 'done',
    'ideas', 'drafts', 'unpublished', 'published', 'archive'
  ];
  v_valid_card_types TEXT[] := ARRAY[
    'epic', 'task', 'bug', 'chore', 'research', 'article'
  ];
  v_valid_priorities TEXT[] := ARRAY[
    'critical', 'high', 'normal', 'low'
  ];
  v_valid_delegation TEXT[] := ARRAY['BENDER', 'DEA'];
  v_valid_bender_lanes TEXT[] := ARRAY[
    'proposed', 'queued', 'executing', 'delivered', 'integrated'
  ];
BEGIN
  -- ── 1. Required field check ──────────────────────────────────
  IF p_title IS NULL OR trim(p_title) = '' THEN
    RAISE EXCEPTION 'p_title is required and cannot be empty';
  END IF;

  -- ── 2. Enum validation (clear errors before hitting CHECK) ───
  IF p_card_type != ALL(v_valid_card_types) THEN
    RAISE EXCEPTION 'Invalid card_type: %. Valid values: %',
      p_card_type, array_to_string(v_valid_card_types, ', ');
  END IF;

  IF p_lane != ALL(v_valid_lanes) THEN
    RAISE EXCEPTION 'Invalid lane: %. Valid values: %',
      p_lane, array_to_string(v_valid_lanes, ', ');
  END IF;

  IF p_priority != ALL(v_valid_priorities) THEN
    RAISE EXCEPTION 'Invalid priority: %. Valid values: %',
      p_priority, array_to_string(v_valid_priorities, ', ');
  END IF;

  IF p_delegation_tag != ALL(v_valid_delegation) THEN
    RAISE EXCEPTION 'Invalid delegation_tag: %. Valid values: BENDER, DEA',
      p_delegation_tag;
  END IF;

  IF p_bender_lane IS NOT NULL AND p_bender_lane != ALL(v_valid_bender_lanes) THEN
    RAISE EXCEPTION 'Invalid bender_lane: %. Valid values: %',
      p_bender_lane, array_to_string(v_valid_bender_lanes, ', ');
  END IF;

  -- ── 3. Project slug → UUID ───────────────────────────────────
  SELECT id INTO v_project_id
  FROM nexus_projects
  WHERE slug = p_project_slug;

  IF v_project_id IS NULL THEN
    RAISE EXCEPTION
      'Unknown project_slug: %. Valid slugs: council, nexus, control-center, kerkoporta, kerkoporta-writing, job-search',
      p_project_slug;
  END IF;

  -- ── 4. Parent card_id (text) → UUID ─────────────────────────
  IF p_parent_card_id IS NOT NULL THEN
    SELECT id INTO v_parent_uuid
    FROM nexus_cards
    WHERE card_id = p_parent_card_id;

    IF v_parent_uuid IS NULL THEN
      RAISE EXCEPTION 'Parent card not found: %', p_parent_card_id;
    END IF;
  END IF;

  -- ── 5. INSERT nexus_cards ────────────────────────────────────
  -- card_id intentionally omitted: BEFORE INSERT trigger
  -- nexus_card_auto_id → nexus_generate_card_id() sets it from
  -- nexus_projects.card_id_prefix + next_card_number (row-locked).
  INSERT INTO nexus_cards (
    project_id,
    parent_id,
    title,
    summary,
    card_type,
    lane,
    bender_lane,
    priority,
    delegation_tag,
    delegation_justification,
    assigned_to,
    assigned_model,
    source,
    tags
  ) VALUES (
    v_project_id,
    v_parent_uuid,
    trim(p_title),
    p_summary,
    p_card_type,
    p_lane,
    p_bender_lane,
    p_priority,
    p_delegation_tag,
    p_delegation_justification,
    p_assigned_to,
    p_assigned_model,
    p_source,
    COALESCE(p_tags, '{}')
  )
  RETURNING id, card_id INTO v_card_uuid, v_card_id;

  -- ── 6. INSERT nexus_task_details (only if overview provided) ─
  -- card_id column in nexus_task_details is UUID FK to nexus_cards.id
  IF p_overview IS NOT NULL THEN
    INSERT INTO nexus_task_details (
      card_id,
      overview,
      requirements,
      acceptance_criteria,
      deliverables,
      constraints
    ) VALUES (
      v_card_uuid,
      p_overview,
      p_requirements,
      p_acceptance_criteria,
      p_deliverables,
      p_constraints
    );
  END IF;

  -- ── 7. Return ────────────────────────────────────────────────
  RETURN QUERY SELECT v_card_id, v_card_uuid, p_project_slug;
END;
$$;

-- Grant to standard Supabase roles
GRANT EXECUTE ON FUNCTION create_nexus_card TO authenticated;
GRANT EXECUTE ON FUNCTION create_nexus_card TO service_role;

COMMENT ON FUNCTION create_nexus_card IS
  'Validated single-entry-point for nexus_cards creation. Resolves project_slug to UUID,
   validates all enum fields with clear error messages, and optionally creates a
   nexus_task_details row when p_overview is provided.
   card_id is auto-generated by the nexus_card_auto_id BEFORE INSERT trigger.
   Returns: (out_card_id TEXT, out_card_uuid UUID, out_project_slug TEXT).
   Created: 2026-02-19.';
